version: '3.7'

services:
  planningpoker:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
